In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
Learning_rates_array = [1, 10**-1, 10**-2, 10**-3, 10**-4, 10**-5, 10**-6, 10**-7, 10**-8, 10**-9]
classifiers_array = np.zeros((100,785,1))
for i in range(0,100):
    classifiers_array[i][0][0] = 1

In [3]:
## READING TRAINING PHASE IMAGES
x = np.zeros((2400, 785,1))
for i in range(1, 2401):
    image_dir = f"/Users/amrabuelfadl/Desktop/ML/Assignment 2_30913/Train/{i}.jpg" #Directory should be changed
    image = plt.imread(image_dir)
    inputPixels = np.array(image)
    image_width = 0
    image_height = 0
    x[i-1][784] = 1
    for j in range(784):
        if image_width == 28:
            image_width = 0
            image_height += 1
        x[i-1][j] = inputPixels[image_height][image_width]
        image_width += 1
    x[i-1] = np.reshape(x[i-1],(785,1))
print("done")   
x[0].shape

done


(785, 1)

In [4]:
t = np.ones((2400, 1))
t[0:240] = 0
t[240:480] = 1
t[480:720] = 2
t[720:960] = 3
t[960:1200] = 4
t[1200:1440] = 5
t[1440:1680] = 6
t[1680:1920] = 7
t[1920:2160] = 8
t[2160:] = 9

In [5]:
## TRAINING PHASE

idx = -1
for lRate in Learning_rates_array:
    idx += 1
    for classifier in range(idx*10 , idx*10+10):
        array_of_t = np.ones((2400,1))
        labels = np.negative(array_of_t)
        labels[240 * (classifier % 10) : 240 + (240 * (classifier % 10))] = 1
        for iteration in range(500):
            for image in range(x.shape[0]):
                p = np.dot(classifiers_array[classifier].flatten(), x[image])
                if p >= 0:
                    p = 1
                else:
                    p = -1

                if p != labels[image]: 
                    classifiers_array[classifier] += lRate * x[image] * labels[image]                  
        labels[240 * (classifier % 10) : 240 + (240 * (classifier % 10))] = -1

In [6]:
## READING TEST IMAGES

x_Test = np.zeros((200, 785,1))
for i in range(1, 201):
    image_dir = f"/Users/amrabuelfadl/Desktop/ML/Assignment 2_30913/Test/{i}.jpg" #Directory should be changed
    image = plt.imread(image_dir)
    inputPixels = np.array(image)
    image_width = 0
    image_height = 0
    x_Test[i-1][784] = 1
    for j in range(784):
        if image_width == 28:
            image_width = 0
            image_height += 1
        x_Test[i-1][j] = inputPixels[image_height][image_width]
        image_width += 1
    x_Test[i-1] = np.reshape(x_Test[i-1],(785,1))
    

In [7]:
t_test = np.ones((200, 1))
t_test[0:20] = 0
t_test[20:40] = 1
t_test[40:60] = 2
t_test[60:80] = 3
t_test[80:100] = 4
t_test[100:120] = 5
t_test[120:140] = 6
t_test[140:160] = 7
t_test[160:180] = 8
t_test[180:] = 9

In [8]:
## TEST PHASE

output_Learningrate_1 = np.zeros((10, 10), dtype = int)
output_Learningrate_2 = np.zeros((10, 10), dtype = int)
output_Learningrate_3 = np.zeros((10, 10), dtype = int)
output_Learningrate_4 = np.zeros((10, 10), dtype = int)
output_Learningrate_5 = np.zeros((10, 10), dtype = int)
output_Learningrate_6 = np.zeros((10, 10), dtype = int)
output_Learningrate_7 = np.zeros((10, 10), dtype = int)
output_Learningrate_8 = np.zeros((10, 10), dtype = int)
output_Learningrate_9 = np.zeros((10, 10), dtype = int)
output_Learningrate_10 = np.zeros((10, 10), dtype = int)
cnt = 0
cnt1 = 0
cnt2 = 0
cnt3 = 0
cnt4 = 0
cnt5 = 0
cnt6 = 0
cnt7 = 0
cnt8 = 0
cnt9 = 0
cnt10 = 0

counter = 0
for i in range(1,len(x_Test)+1):
    max = -np.inf
    label = -1
    for lr in range(10):
        for j in range(10*lr,10*lr + 10):
            p = np.dot(classifiers_array[j].flatten(), x_Test[i-1])
            if p > max:
                max = p
                label = j % 10

    ####################### checking for accuracing
        if lr == 0 and label == t_test[i-1]: 
            cnt1 += 1
        
        if lr == 1 and label == t_test[i-1]: 
            cnt2 += 1
            
        if lr == 2 and label == t_test[i-1]: 
            cnt3 += 1
            
        if lr == 3 and label == t_test[i-1]: 
            cnt4 += 1
            
        if lr == 4 and label == t_test[i-1]: 
            cnt5 += 1
            
        if lr == 5 and label == t_test[i-1]: 
            cnt6 += 1
             
        if lr == 6 and label == t_test[i-1]: 
            cnt7 += 1
            
        if lr == 7 and label == t_test[i-1]: 
            cnt8 += 1
            
        if lr == 8 and label == t_test[i-1]: 
            cnt9 += 1
            
        if lr == 9 and label == t_test[i-1]: 
            cnt10 += 1
        ######################## confusion matrix for each learning rate
        if lr == 0 : 
            output_Learningrate_1[counter][label] += 1        # Confusion matrix for 
           
        
        if lr == 1 : 
            output_Learningrate_2[counter][label] += 1
            
            
        if lr == 2 : 
            output_Learningrate_3[counter][label] += 1  
            
            
        if lr == 3 : 
            output_Learningrate_4[counter][label] += 1
            
            
        if lr == 4 : 
            output_Learningrate_5[counter][label] += 1  
            
            
        if lr == 5: 
            output_Learningrate_6[counter][label] += 1
            
             
        if lr == 6 : 
            output_Learningrate_7[counter][label] += 1  
            
            
        if lr == 7 : 
            output_Learningrate_8[counter][label] += 1  
            
            
        if lr == 8 : 
            output_Learningrate_9[counter][label] += 1
            
            
        if lr == 9 : 
            output_Learningrate_10[counter][label] += 1
            
            
    if (i % 20) == 0:
        counter += 1

print(cnt1/len(x_Test) * 100)
print(cnt2/len(x_Test) * 100)
print(cnt3/len(x_Test) * 100)
print(cnt4/len(x_Test) * 100)
print(cnt5/len(x_Test) * 100)
print(cnt6/len(x_Test) * 100)
print(cnt7/len(x_Test) * 100)
print(cnt8/len(x_Test) * 100)
print(cnt9/len(x_Test) * 100)
print(cnt10/len(x_Test) * 100)



84.5
84.5
84.5
83.5
84.0
83.0
83.5
83.5
83.0
84.0


In [20]:
plt.imsave(f"/Users/amrabuelfadl/Desktop/Confusion-{Learning_rates_array[0]}.jpg", output_Learningrate_1, cmap = "gray")
output_Learningrate_1

array([[19,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0, 18,  1,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  1, 16,  1,  1,  0,  0,  0,  1,  0],
       [ 0,  0,  1, 15,  0,  0,  0,  0,  2,  2],
       [ 0,  0,  0,  0, 17,  1,  0,  0,  0,  2],
       [ 0,  0,  1,  0,  2, 16,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  1, 18,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 15,  0,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 19,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  2,  1, 16]])

In [21]:
plt.imsave(f"/Users/amrabuelfadl/Desktop/Confusion-{Learning_rates_array[1]}.jpg", output_Learningrate_2, cmap = "gray")
output_Learningrate_2

array([[19,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0, 18,  1,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  1, 16,  1,  1,  0,  0,  0,  1,  0],
       [ 0,  0,  1, 15,  0,  0,  0,  0,  2,  2],
       [ 0,  0,  0,  0, 17,  1,  0,  0,  0,  2],
       [ 0,  0,  1,  0,  2, 16,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  1, 18,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 15,  0,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 19,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  2,  1, 16]])

In [22]:
plt.imsave(f"/Users/amrabuelfadl/Desktop/Confusion-{Learning_rates_array[2]}.jpg", output_Learningrate_3, cmap = "gray")
output_Learningrate_3

array([[19,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0, 18,  1,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  1, 16,  1,  1,  0,  0,  0,  1,  0],
       [ 0,  0,  1, 15,  0,  0,  0,  0,  2,  2],
       [ 0,  0,  0,  0, 17,  1,  0,  0,  0,  2],
       [ 0,  0,  1,  0,  2, 16,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  1, 18,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 15,  0,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 19,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  2,  1, 16]])

In [23]:
plt.imsave(f"/Users/amrabuelfadl/Desktop/Confusion-{Learning_rates_array[3]}.jpg", output_Learningrate_4, cmap = "gray")
output_Learningrate_4

array([[19,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0, 18,  1,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  1, 16,  1,  1,  0,  0,  0,  1,  0],
       [ 0,  0,  1, 13,  0,  1,  0,  0,  3,  2],
       [ 0,  0,  0,  0, 17,  1,  0,  0,  0,  2],
       [ 0,  0,  1,  0,  2, 16,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  1, 18,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 15,  0,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 19,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  2,  1, 16]])

In [24]:
plt.imsave(f"/Users/amrabuelfadl/Desktop/Confusion-{Learning_rates_array[4]}.jpg", output_Learningrate_5, cmap = "gray")
output_Learningrate_5

array([[19,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0, 18,  1,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  1, 16,  1,  1,  0,  0,  0,  1,  0],
       [ 0,  0,  1, 14,  0,  1,  0,  0,  3,  1],
       [ 0,  0,  0,  0, 17,  1,  0,  0,  1,  1],
       [ 0,  0,  1,  0,  2, 16,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  1, 18,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 15,  0,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 19,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  2,  1, 16]])

In [25]:
plt.imsave(f"/Users/amrabuelfadl/Desktop/Confusion-{Learning_rates_array[5]}.jpg", output_Learningrate_6, cmap = "gray")
output_Learningrate_6 

array([[19,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0, 18,  1,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  1, 16,  1,  1,  0,  0,  0,  1,  0],
       [ 1,  0,  1, 14,  0,  0,  0,  0,  2,  2],
       [ 0,  1,  0,  0, 16,  1,  0,  0,  0,  2],
       [ 0,  0,  1,  0,  2, 16,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  1, 18,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 14,  0,  6],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 19,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  2,  1, 16]])

In [26]:
plt.imsave(f"/Users/amrabuelfadl/Desktop/Confusion-{Learning_rates_array[6]}.jpg", output_Learningrate_7, cmap = "gray")
output_Learningrate_7 

array([[19,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0, 18,  1,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  1, 16,  1,  1,  0,  0,  0,  1,  0],
       [ 0,  0,  1, 15,  0,  1,  0,  0,  2,  1],
       [ 0,  1,  0,  0, 16,  1,  0,  0,  0,  2],
       [ 0,  0,  1,  0,  2, 16,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  1, 18,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 14,  0,  6],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 19,  1],
       [ 0,  0,  1,  0,  0,  0,  0,  2,  1, 16]])

In [27]:
plt.imsave(f"/Users/amrabuelfadl/Desktop/Confusion-{Learning_rates_array[7]}.jpg", output_Learningrate_8, cmap = "gray")
output_Learningrate_8

array([[19,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0, 18,  1,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  1, 16,  1,  1,  0,  0,  0,  1,  0],
       [ 0,  0,  1, 15,  0,  0,  0,  0,  3,  1],
       [ 0,  0,  0,  0, 16,  2,  0,  0,  0,  2],
       [ 0,  0,  1,  0,  2, 16,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  1, 18,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 14,  0,  6],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 19,  1],
       [ 0,  0,  1,  0,  0,  0,  0,  2,  1, 16]])

In [28]:
plt.imsave(f"/Users/amrabuelfadl/Desktop/Confusion-{Learning_rates_array[8]}.jpg", output_Learningrate_9, cmap = "gray")
output_Learningrate_9 

array([[19,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0, 18,  1,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  1, 16,  1,  1,  0,  0,  0,  1,  0],
       [ 0,  0,  1, 15,  0,  0,  0,  0,  3,  1],
       [ 0,  0,  0,  0, 16,  2,  0,  0,  0,  2],
       [ 0,  0,  1,  0,  2, 16,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  1, 18,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 14,  0,  6],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 19,  1],
       [ 0,  0,  1,  0,  0,  0,  0,  3,  1, 15]])

In [29]:
plt.imsave(f"/Users/amrabuelfadl/Desktop/Confusion-{Learning_rates_array[9]}.jpg", output_Learningrate_10, cmap = "gray")
output_Learningrate_10

array([[19,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0, 18,  1,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  1, 16,  1,  1,  0,  0,  0,  1,  0],
       [ 0,  0,  1, 16,  0,  0,  0,  0,  2,  1],
       [ 0,  0,  0,  0, 17,  2,  0,  0,  0,  1],
       [ 0,  0,  1,  0,  2, 16,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  1, 18,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 14,  0,  6],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 19,  1],
       [ 0,  0,  1,  0,  0,  0,  0,  3,  1, 15]])